version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: scholar-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: scholardb
    volumes:
      - mongodb_data:/data/db
    networks:
      - scholar-network

  # Storage Service (File Upload Handler)
  storage-service:
    build:
      context: ./scholar-database-storage
      dockerfile: Dockerfile
    container_name: scholar-storage
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - storage_uploads:/app/uploads
    networks:
      - scholar-network
    depends_on:
      - mongodb

  # Main Backend API
  backend-api:
    build:
      context: ./scholar-database-backend
      dockerfile: Dockerfile
    container_name: scholar-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - scholar-network
    depends_on:
      - mongodb
      - storage-service

  # Frontend (Next.js)
  frontend:
    build:
      context: ./scholar-database
      dockerfile: Dockerfile
    container_name: scholar-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - scholar-network
    depends_on:
      - backend-api
      - storage-service

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  storage_uploads:
    driver: local

networks:
  scholar-network:
    driver: bridge